export default {
	/**
	*	Register
	*/
	REGISTER_LOADING : 'REGISTER_LOADING',
	REGISTER_FAIL : 'REGISTER_FAIL',
	REGISTER_SUCCESS : 'REGISTER_SUCCESS',
	REGISTER_CHECK_USERNAME_LOADING : 'REGISTER_CHECK_USERNAME_LOADING',
	REGISTER_CHECK_USERNAME_FAIL : 'REGISTER_CHECK_USERNAME_FAIL',
	REGISTER_CHECK_USERNAME_SUCCESS : 'REGISTER_CHECK_USERNAME_SUCCESS',
	REGISTER_CHECK_PASSWORD_FAIL : 'REGISTER_CHECK_PASSWORD_FAIL',
	REGISTER_CHECK_PASSWORD_SUCCESS : 'REGISTER_CHECK_PASSWORD_SUCCESS',


	/**
	*	Auth
	*/
	AUTH_CHECK_AUTH_STARTED : 'AUTH_CHECK_AUTH_STARTED',
	AUTH_CHECK_AUTH_SUCCESS : 'AUTH_CHECK_AUTH_SUCCESS',
	AUTH_CHECK_AUTH_FAIL : 'AUTH_CHECK_AUTH_FAIL',
	AUTH_LOGOUT : 'AUTH_LOGOUT',
	AUTH_LOGIN_LOADING : 'AUTH_LOGIN_LOADING',
	AUTH_LOGIN_SUCCESS : 'AUTH_LOGIN_SUCCESS',
	AUTH_LOGIN_FAIL : 'AUTH_LOGIN_FAIL',
	AUTH_AFTER_REGISTRATION_LOGIN : 'AUTH_AFTER_REGISTRATION_LOGIN',
	AUTH_LOADING : 'AUTH_LOADING',
	AUTH_GET_USER_INFO_SUCCESS : 'AUTH_GET_USER_INFO_SUCCESS',
	AUTH_GET_USER_INFO_FAIL : 'AUTH_GET_USER_INFO_FAIL',



	/**
	*	Page
	*/
	PAGE_SET_HISTORY_OBJECT : 'PAGE_SET_HISTORY_OBJECT',
	PAGE_REDIRECT_TO : 'PAGE_REDIRECT_TO',
	PAGE_POP_STATE : 'PAGE_POP_STATE',
}