export default {
	CHECK_AUTH_STARTED : 'CHECK_AUTH_STARTED',
	CHECK_AUTH_SUCCESS : 'CHECK_AUTH_SUCCESS',
	CHECK_AUTH_FAIL : 'CHECK_AUTH_FAIL',
	SET_HISTORY_OBJECT : 'SET_HISTORY_OBJECT',
	REDIRECT_TO : 'REDIRECT_TO',
	LOGOUT : 'LOGOUT',
	LOGIN_TRY : 'LOGIN_TRY',
	LOGIN_RESULT : 'LOGIN_RESULT',
	AFTER_REGISTRATION_LOGIN : 'AFTER_REGISTRATION_LOGIN',
}